### ISSUE TITLE
two errors

### ISSUE THREAD

**Issue by kacperleague9** [LeonZ2019/dbm-interactions#1]
Hello, I found two errors

1 in your dbm canvas:
`(node:7000) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'customData' of undefined
    at Object.mod (D:\Desktop\EagleBotv2\EagleBot2\extensions\canvas_EXT.js:57:19)
    at Object.<anonymous> (D:\Desktop\EagleBotv2\EagleBot2\bot.js:368:14)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (D:\Desktop\EagleBotv2\EagleBot2\bot.js:360:23)
    at Array.forEach (<anonymous>)
    at Object.Actions.initMods (D:\Desktop\EagleBotv2\EagleBot2\bot.js:359:24)
    at Object.Files.startBot (D:\Desktop\EagleBotv2\EagleBot2\bot.js:1150:11)
    at Object.<anonymous> (D:\Desktop\EagleBotv2\EagleBot2\bot.js:1848:7)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:7000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

second in interactions: 
`(node:7000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
D:\Desktop\EagleBotv2\EagleBot2\node_modules\discord.js\src\client\Client.js:474
      throw new TypeError('CLIENT_MISSING_INTENTS');
      ^

TypeError [CLIENT_MISSING_INTENTS]: Valid intents must be provided for the Client.
    at Client._validateOptions (D:\Desktop\EagleBotv2\EagleBot2\node_modules\discord.js\src\client\Client.js:474:13)
    at new Client (D:\Desktop\EagleBotv2\EagleBot2\node_modules\discord.js\src\client\Client.js:77:10)
    at Object.Bot.initBot (D:\Desktop\EagleBotv2\EagleBot2\bot.js:41:13)
    at Object.Bot.init (D:\Desktop\EagleBotv2\EagleBot2\bot.js:33:7)
    at Object.<anonymous> (D:\Desktop\EagleBotv2\EagleBot2\bot.js:1181:5)
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3) {
  [Symbol(code)]: 'CLIENT_MISSING_INTENTS'
}`

**Comment by LeonZ2019** [comment]
1. You might have outdated canvas mod
2. Current bot.js is not compatible with this mod and this mod is not finish yet

**Comment by kacperleague9** [comment]
i have latest canvas mod downloaded like 2 days ago

**Comment by LeonZ2019** [comment]
still not a place to issue

**Comment by kacperleague9** [comment]
i cant make issues on dbm canvas
